apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
data:
  MYSQL_USER: cm9vdAo=
  MYSQL_PASSWORD: YWRtaW4K     
  MYSQL_DB: bXlkYgo=
  MYSQL_DATABASE: bXlkYgo=
  MYSQL_ROOT_PASSWORD: YWRtaW4K

  