apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-app
        image: nishdoc1999/flaskapp:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "10.107.205.241"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
        - name: MYSQL_USER
          value: "root"
       
        



        
        
